:host = http://localhost:3000
:todos = :host/todos

# create
# Expect: 200 OK
# Response: HTTP/1.1 200 OK
# Result: Passed
POST :todos
Content-Type: application/json

{
"title": "test #1",
"date": "2019-06-29T23:59:59Z",
"done": false
}

# get all
# Expect: 200 OK
# Response: HTTP/1.1 200 OK
# Result: Passed
GET :todos

# get
# Expect: 200 OK
# Response: HTTP/1.1 200 OK
# Result: Passed
GET :todos/1

# update
# Expect: 200 OK
# Response: HTTP/1.1 200 OK
# Result: Passed
PUT :todos/1
Content-Type: application/json

{
"title": "test #2",
"date": "2018-06-29T23:59:59Z",
"done": true
}

# delete
# Expect: 200 OK
# Response: HTTP/1.1 200 OK
# Result: Passed
DELETE :todos/1

# metrics
# Expect: 200 OK
# Response: HTTP/1.1 200 OK
# Result: Passed
GET :host/metrics

# health
# Expect: 200 OK
# Response: HTTP/1.1 200 OK
# Result: Passed
GET :host/health
