version: "3"
services:
  postgres:
    image: "postgres:alpine"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: secret
  todo:
    depends_on:
      - postgres
    image: "todo-clj"
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      DB_HOST: postgres
